apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naresh-pvc
spec:
  storageClassName: standard
  volumeName: my-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
